version: '3'
services:
  app:
    container_name: inventory_web_app
    image: inventory_web_app
    build: .
    networks:
      - main_network
    ports:
      - '2021:2021'
    volumes:
      - .:/app
      - /app/node_modules

  database:
    container_name: database
    image: mongo
    volumes:
      - /data/db/mongo
    ports:
      - '27017:27017'
    networks:
      - main_network
volumes:
  node_modules:

networks:
  main_network:
    driver: bridge
